apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume-nfs
  namespace: apache-exposed
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
