apiVersion: v1
kind: Service
metadata: 
  name: nodeportservice-for-apache
  namespace: apache-exposed
spec:
  type: Loadbalancer 
  ports:
    - targetPort: 80
      protocol: TCP
      port: 80
      nodePort: 30001
  selector:
    app: httpd-ex
