apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-external-deployment
  namespace: apache-exposed
  labels:
    app: apache-external
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-ex
  template:
    metadata:
      labels:
        app: httpd-ex
    spec:
      volumes:
        - name: apache-hdd
          persistentVolumeClaim:
            claimName: pvc-volume-nfs 
      containers:
        - name: httpd-exp
          image: httpd:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/local/apache2/htdocs"
              name: apache-hdd
